services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs,sns,dynamodb,lambda
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"